import type { Photo } from '@/lib/manifest/types';

export const encontroPhotos: Photo[] = [
  {
    id: 'o-encontro-1-1',
    src: '/o%20encontro/1%20(1).webp',
    width: 4000,
    height: 6000,
    aspectRatio: 4000 / 6000,
    chapter: 'olhares',
    role: 'narrative',
    narrativeOrder: 13,
    discoveryOrder: 6,
    focalPoint: { x: 50, y: 50 },
    placeholder:
      'data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAAAwBACdASoQABgAPzmEuVOvKKWisAgB4CcJagC7AB3twMt0edTOWwUVJQAAzjVt8D0MOQo+sBMGyqbd8voITS1ySvSSeoANAv81KNWK+fGwpIiBW4gNc3CttmQ3BRFtbLDpdMZTg3Djzawz5khDLInJaxVquG6gBR5XXIyJ5ZLo3oKtyBYAAA==',
    variants: [
      {
        src: '/o%20encontro/1%20(1).webp',
        width: 1067,
        height: 1600,
        format: 'webp',
        bytes: 170496,
      },
    ],
    alt: 'Marina e Thiago de mãos dadas em oração diante do altar.',
    orientation: 'portrait',
    cropTolerance: 'normal',
    featured: true,
  },
  {
    id: 'o-encontro-3',
    src: '/o%20encontro/3.webp',
    width: 4000,
    height: 6000,
    aspectRatio: 4000 / 6000,
    chapter: 'olhares',
    role: 'narrative',
    narrativeOrder: 14,
    discoveryOrder: 7,
    focalPoint: { x: 50, y: 50 },
    placeholder:
      'data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAAAwBACdASoQABgAPzmGuVOvKSWisAgB4CcJZADCgCFJF++hbHDk44uGEQAA38ocDycBcb9aFO6+t3yK26A3FEbOP+dAqAPPPR2+cgi4EPHpbzGjwW4qzuAZDq/uAtugtcIaRz+mVmyik28QJ7KbBliSNi/yZ/Q3/zcoOUtJbezAkGrcPyTGdOZGVSu/WPtDDivcAA==',
    variants: [
      {
        src: '/o%20encontro/3.webp',
        width: 1067,
        height: 1600,
        format: 'webp',
        bytes: 199168,
      },
    ],
    alt: 'Marina e Thiago em oração no altar sob a brisa do entardecer.',
    orientation: 'portrait',
    cropTolerance: 'normal',
    featured: true,
  },
  {
    id: 'o-encontro-20',
    src: '/o%20encontro/20.webp',
    width: 4000,
    height: 6000,
    aspectRatio: 4000 / 6000,
    chapter: 'olhares',
    role: 'narrative',
    narrativeOrder: 15,
    discoveryOrder: 8,
    focalPoint: { x: 50, y: 50 },
    placeholder:
      'data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADwAwCdASoQABgAPzmEuVOvKKWisAgB4CcJQBdgA6aNZZnncrw9GZkAAP6DZl5D8dqMmPFlyvK8xJbTTh7ChF6qJKNSv5pzn/PKRe4JWIq3ITrk74GqbNAYExp0CdH88jp0y4TlM6lz/vBS8oqjZwjhXIu4AAAA',
    variants: [
      {
        src: '/o%20encontro/20.webp',
        width: 1067,
        height: 1600,
        format: 'webp',
        bytes: 248320,
      },
    ],
    alt: 'Visão lateral de Marina e Thiago no altar com os convidados ao fundo.',
    orientation: 'portrait',
    cropTolerance: 'normal',
    featured: true,
  },
  {
    id: 'o-encontro-25',
    src: '/o%20encontro/25.webp',
    width: 4000,
    height: 6000,
    aspectRatio: 4000 / 6000,
    chapter: 'olhares',
    role: 'narrative',
    narrativeOrder: 16,
    discoveryOrder: 9,
    focalPoint: { x: 50, y: 50 },
    placeholder:
      'data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAABwBACdASoQABgAPzmEuVOvKKWisAgB4CcJQBOkBshTaVrrgVZQBGCxO1SsAAD4RYogv6FYOsotaVt4fFWYjYFc+4quOWOreoelReGrR667djnTwdIR4TBNq3MCqFWMDP5D2d9LXGKEHaScO3r2uvxtkLaCsahTkUX4/TYFXip2xK5mhPTcH7aYAaUAAA==',
    variants: [
      {
        src: '/o%20encontro/25.webp',
        width: 1067,
        height: 1600,
        format: 'webp',
        bytes: 251084,
      },
    ],
    alt: 'Marina e Thiago sorrindo com cumplicidade durante a celebração.',
    orientation: 'portrait',
    cropTolerance: 'normal',
    featured: true,
  },
  {
    id: 'o-encontro-37',
    src: '/o%20encontro/37.webp',
    width: 4000,
    height: 6000,
    aspectRatio: 4000 / 6000,
    chapter: 'olhares',
    role: 'narrative',
    narrativeOrder: 17,
    discoveryOrder: 10,
    focalPoint: { x: 50, y: 50 },
    placeholder:
      'data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAAAQBACdASoQABgAPzmEuVOvKKWisAgB4CcJZgC06CHPSpmD288DYz8KAAD+4uhlpYIeewczw9Rp09d1SM3z4yhxwYb6uECXqxymUzW3uS+/BWbpULNFkNQ6rFWWPKg+DdIN8PKrN0hUV7LHCftEi4P4hQ2tjAJ3snkAAA==',
    variants: [
      {
        src: '/o%20encontro/37.webp',
        width: 1067,
        height: 1600,
        format: 'webp',
        bytes: 188723,
      },
    ],
    alt: 'Marina e Thiago dando gargalhadas juntos sob as luzes da praia.',
    orientation: 'portrait',
    cropTolerance: 'normal',
    featured: true,
  },
  {
    id: 'o-encontro-42',
    src: '/o%20encontro/42.webp',
    width: 4000,
    height: 6000,
    aspectRatio: 4000 / 6000,
    chapter: 'olhares',
    role: 'narrative',
    narrativeOrder: 18,
    discoveryOrder: 11,
    focalPoint: { x: 50, y: 50 },
    placeholder:
      'data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAAAQBACdASoQABgAPzmEuVOvKKWisAgB4CcJQBWAO4AekPRg8WwHQOpgQAD+y7RykEC/LcT0XEqHTmdP7252O6XFWpUwZmvshmGvOthB6pfKB6/j508rDe+txC7SJp8k0QphPNHonc44CQmhN+rsMbqNsB+ZKXldcopWoi7uAAA=',
    variants: [
      {
        src: '/o%20encontro/42.webp',
        width: 1067,
        height: 1600,
        format: 'webp',
        bytes: 202547,
      },
    ],
    alt: 'Marina e Thiago de mãos dadas com olhar sereno e apaixonado.',
    orientation: 'portrait',
    cropTolerance: 'normal',
    featured: true,
  },
];
