export type Chapter = 'preparacao' | 'comeco' | 'olhares' | 'cerimonia' | 'sim' | 'festa' | 'memoria';
export type EditorialEntry = { chapter: Chapter; order?: number; alt: string; focal?: [number, number]; role?: string };
const entry = (chapter: Chapter, alt: string, order?: number, focal?: [number, number], role?: string): EditorialEntry => ({ chapter, alt, order, focal, role });
// Editorial decisions made after inspecting all 77 photographs, not inferred from filenames.
export const editorial: Record<string, EditorialEntry> = {
  'Preparação/IMG_9232.jpg': entry('preparacao', 'Thiago ajusta o paletó claro diante de um portão de madeira.', 1, [48, 48], 'opening'),
  'Preparação/IMG_9359.jpg': entry('preparacao', 'Marina de costas, com a cauda do vestido estendida no caminho do jardim.', 2),
  'Preparação/IMG_9460.jpg': entry('preparacao', 'Marina sorri olhando para o buquê branco, diante da vegetação.', 3, [60, 50], 'detail'),
  'Preparação/IMG_9349.jpg': entry('preparacao', 'Marina abraça Thiago por trás no jardim.', 4),
  'Preparação/IMG_9351.jpg': entry('preparacao', 'O casal junto no caminho do jardim, diante da casa.'),
  'Preparação/IMG_9364.jpg': entry('preparacao', 'Marina e Thiago abraçados sob as palmeiras do jardim.'),
  'Preparação/IMG_9517.jpg': entry('comeco', 'Marina sorri dentro do carro com o buquê nas mãos.', 6, [53, 55]),
  'Preparação/IMG_9568.jpg': entry('comeco', 'Marina olha pela janela aberta do carro na chegada.', 7, [64, 48]),
  'Celebração/IMG_9623.jpg': entry('comeco', 'A cruz de madeira e o altar diante do mar, ainda sob a luz do dia.', 5, [50, 50], 'environment'),
  'Celebração/IMG_9642.jpg': entry('comeco', 'A cruz de madeira, uma palmeira e folhas verdes à beira-mar.'),
  'Celebração/IMG_9732.jpg': entry('comeco', 'Thiago caminha acompanhado de uma mulher pelo corredor da cerimônia.'),
  'Celebração/IMG_9914.jpg': entry('comeco', 'Convidados voltados para o corredor entre bancos de madeira e palmeiras.', 8, [50, 60], 'environment'),
  'Celebração/IMG_9932.jpg': entry('comeco', 'Marina caminha acompanhada em direção ao altar, com a cauda do vestido na areia.', 9, [50, 60], 'handoff-source'),
  'Celebração/IMG_9821.jpg': entry('olhares', 'Thiago espera diante da cruz, com o olhar voltado para o corredor.', 10, [36, 44], 'reaction'),
  'Celebração/GAB06805.jpg': entry('olhares', 'Marina se aproxima ao fundo enquanto Thiago aparece em primeiro plano.', 11, [48, 45], 'recognition'),
  'Celebração/IMG_9987.jpg': entry('olhares', 'Marina se aproxima do rosto de Thiago junto ao altar.', 12),
  'Celebração/IMG_9895.jpg': entry('olhares', 'Thiago com as mãos juntas e o rosto voltado para cima, sob as luzes.'),
  'Celebração/IMG_9981.jpg': entry('olhares', 'Marina e Thiago sorriem lado a lado no altar.'),
  'Celebração/IMG_0130.jpg': entry('cerimonia', 'Vista ampla da cerimônia: casal, convidados e mar azul ao entardecer.', 13, [51, 52], 'environment'),
  'Celebração/IMG_0169.jpg': entry('cerimonia', 'Marina apoia a cabeça no ombro de Thiago durante a cerimônia.', 14, [48, 52], 'reaction'),
  'Celebração/IMG_0182.jpg': entry('cerimonia', 'O casal de costas diante do celebrante, sob as luzes e o céu azul profundo.', 15),
  'Celebração/GAB07176.jpg': entry('cerimonia', 'Fotografia em preto e branco das mãos do casal segurando taças.', 16, [50, 52], 'detail'),
  'Celebração/56.jpg': entry('cerimonia', 'Marina e Thiago seguram taças ao lado da mesa do altar.', 17, [50, 46], 'ritual'),
  'Celebração/IMG_0525.jpg': entry('cerimonia', 'Duas alianças douradas repousam em uma concha na palma de uma mão.', 18, [52, 55], 'detail'),
  'Celebração/IMG_0534.jpg': entry('cerimonia', 'Plano aberto do casal durante a troca de alianças à noite.', 19),
  'Celebração/IMG_0537.jpg': entry('cerimonia', 'Marina e Thiago trocam alianças diante da cruz iluminada.', 20, [50, 54], 'ritual'),
  'Beijo/IMG_0590.jpg': entry('sim', 'Thiago inclina Marina em um beijo diante do altar e das luzes.', 21, [51, 59], 'climax'),
  'Beijo/IMG_0636.jpg': entry('sim', 'O casal se beija entre os convidados; Marina ergue o buquê branco.', 22, [51, 56], 'climax'),
  'Saída/113.jpg': entry('festa', 'Marina e Thiago caminham entre convidados sob uma chuva de pétalas.'),
  'Saída/IMG_0677.jpg': entry('festa', 'Marina ergue o buquê enquanto o casal atravessa as pétalas e os convidados.', 23, [49, 50], 'release'),
  'Saída/IMG_0684.jpg': entry('festa', 'O casal ri no corredor enquanto pétalas atravessam a fotografia.', 24, [51, 54], 'release'),
  'Festa/183.jpg': entry('festa', 'O casal se beija no centro de um brinde coletivo com taças erguidas.', 26, [48, 52], 'party-hero'),
  'Festa/186.jpg': entry('festa', 'Braços e taças se encontram em um brinde ao redor do casal.', 27),
  'Festa/187.jpg': entry('festa', 'Marina e Thiago brindam olhando um para o outro.'),
  'Festa/188.jpg': entry('festa', 'Marina e Thiago tomam suas bebidas durante o brinde.'),
  'Festa/189.jpg': entry('festa', 'Marina sorri abraçada a Thiago durante a festa.', 28),
  'Festa/IMG_1497.jpg': entry('festa', 'Casal e convidados riem juntos ao redor de uma mesa.', 29),
  'Festa/IMG_1507.jpg': entry('festa', 'Marina e Thiago posam com convidados atrás de uma mesa decorada.', 30),
  'Festa/IMG_1514.jpg': entry('festa', 'Um grupo de convidados se reúne com o casal à noite.'),
  'Festa/IMG_1519.jpg': entry('festa', 'Convidados e casal celebram juntos com braços erguidos.', 31),
  'Festa/IMG_1524.jpg': entry('festa', 'Convidadas fazem gestos descontraídos ao redor do casal.', 32),
  'Festa/IMG_1533.jpg': entry('festa', 'Um grande grupo se reúne ao redor de uma mesa com Marina e Thiago.'),
  'Festa/IMG_1543.jpg': entry('festa', 'Casal e convidados sorriem sob o cordão de luzes.'),
  'Festa/IMG_1549.jpg': entry('festa', 'Thiago é erguido por convidados enquanto Marina sorri ao lado do grupo.', 33, [51, 47], 'action'),
  'Festa/IMG_1574.jpg': entry('festa', 'Convidados levantam Thiago horizontalmente, cercados de risadas.', 34, [51, 49], 'reaction'),
  'Festa/IMG_1580.jpg': entry('festa', 'Marina e Thiago posam com convidados em um momento descontraído.'),
  'Festa/IMG_1598.jpg': entry('festa', 'Marina recebe abraços em um grupo sorridente de convidados.'),
  'Festa/IMG_1610.jpg': entry('festa', 'O casal reunido com convidados ao redor de uma mesa de madeira.'),
  'Festa/IMG_1797.jpg': entry('festa', 'Marina abraçada a duas convidadas, sorrindo na festa.', 35),
  'Nossos passos/159.jpg': entry('memoria', 'Marina e Thiago se beijam na areia, com o mar escuro ao fundo.'),
  'Nossos passos/160.jpg': entry('memoria', 'Marina e Thiago caminham de mãos dadas à beira do mar à noite.'),
  'Nossos passos/161.jpg': entry('memoria', 'O casal caminha na areia com a cauda do vestido acompanhando o movimento.'),
  'Nossos passos/162.jpg': entry('memoria', 'Marina e Thiago de mãos dadas, olhando um para o outro na praia.'),
  'Nossos passos/164.jpg': entry('memoria', 'Marina e Thiago sorriem um para o outro, juntos na praia à noite.', 36, [50, 57], 'epilogue'),
  'Nossos passos/165.jpg': entry('memoria', 'Detalhe dos pés descalços do casal e da barra do vestido sobre a areia.'),
  'Nossos passos/167.jpg': entry('memoria', 'A espuma do mar alcança os pés descalços do casal.'),
};
const decor: Record<string, string> = {
  '12': 'Bolo branco de vários andares entre flores e doces.',
  '13': 'Doces com morangos dispostos em uma travessa escura.',
  '14': 'Pequenos doces com folhas verdes sobre a mesa de madeira.',
  '15': 'Bolo branco diante do mar, cercado de flores.',
  '16': 'Cesta de madeira com doces de chocolate e folhagens.',
  '17': 'Travessas de doces variados sobre a mesa de madeira.',
  '18': 'Doces brancos alinhados ao lado da base do bolo.',
  'GAB06390': 'Pequenos frascos azuis organizados sobre uma mesa.',
  'GAB06391': 'Lembranças embaladas e amarradas com fitas verdes.',
  'GAB06394': 'Cesta de lembranças com laços verdes.',
  'GAB06397': 'Bolo decorado com morangos sobre uma base de palha.',
  'GAB06447': 'Taças, flores brancas e jogo americano de palha na mesa.',
  'GAB06449': 'Placa de boas-vindas ao casamento de Marina e Thiago.',
  'GAB06455': 'Mesa posta com taças, flores brancas e fibras naturais.',
  'GAB06470': 'Grande folha verde e uma flor amarela na decoração.',
  'GAB06487': 'Fileiras de doces cobertos com morangos.',
  'GAB06489': 'Doces e flores brancas na mesa de madeira.',
  'GAB06494': 'Mesa do bolo decorada com flores brancas ao entardecer.',
  'GAB06505': 'Cestas de lembranças com fitas verdes sobre um aparador.',
  'IMG_0069': 'Mesa do bolo diante do mar azul, sob luminárias de fibras naturais.',
  'IMG_0073': 'Bolo branco e doces sob a iluminação quente da recepção.',
};
for (const [id, alt] of Object.entries(decor)) {
  editorial[`Decoração/${id}.jpg`] = entry(id.startsWith('GAB') && id !== 'GAB06494' ? 'comeco' : 'festa', alt, id === 'IMG_0069' ? 25 : undefined, [50, 50], 'detail');
}
